FROM python:3.8-slim-buster

WORKDIR /app

COPY src/c21server/work_server/* .

RUN python3 -m venv .venv
RUN .venv/bin/pip install flask redis gunicorn

CMD [".venv/bin/gunicorn", "--bind", "0.0.0.0:8080", "--timeout", "120", "-m", "007", "wsgi:app"]