Vagrant.configure("2") do |config|
  # Set the hardware parameters of the VM
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  # Import the Ubuntu image
  config.vm.box = "ubuntu/bionic64"

  # Configure the network settings for the VM
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.synced_folder "../src/c21server/data", "/data"

  # Provision the VM
  config.vm.provision "shell", inline: <<-SHELL

    # Install all necessary packages for the VM
    apt-get update && apt-get upgrade -y
    apt-get install -y python3-venv python3-pip redis-server nginx openssl

    # Clone the repo and enter the local repo
    git clone https://github.com/cs334s21/capstone2021.git
    ln -s /data capstone2021/src/c21server/data
    cd capstone2021


    # Create the virtual environment and install all necessary packages
    python3 -m venv .venv
    .venv/bin/pip install -e .
    .venv/bin/pip install gunicorn wheel


    # Move the scripts/config files to the necessary folders
    cp -v scripts/*.service /etc/systemd/system
    cp scripts/app /etc/nginx/sites-available/
    ln -s /etc/nginx/sites-available/app /etc/nginx/sites-enabled
    rm /etc/nginx/sites-enabled/default


    # Start all services
    systemctl start workgen
    systemctl enable workgen
    systemctl start workserver
    systemctl enable workserver
    systemctl start dashboard
    systemctl enable dashboard

    # Reload NGINX so the config is replaced
    nginx -s reload



    SHELL

end
